pipelines:
  branches:
    main:
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
            - cd merchandise-hiduka.git
            - git remote add github git@github.com:brill3000/merchandise-hiduka.git
            - git fetch --tags github "+refs/*:refs/*"
            # Debugging - Log commit details before push
            - git log --oneline -n 10  # Log the last 10 commits to check if there are new commits
            - git status  # Check the status of the repository
            - git push github 'refs/heads/main'
    release/pre-release:
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
            - cd merchandise-hiduka.git
            - git remote add github git@github.com:brill3000/merchandise-hiduka.git
            - git fetch --tags github "+refs/*:refs/*"
            # Debugging - Log commit details before push
            - git log --oneline -n 10  # Log the last 10 commits to check if there are new commits
            - git status  # Check the status of the repository
            - git push github 'refs/heads/release/pre-release'

