pipelines:
  branches:
    main:
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: true
          script:
            - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
            - cd merchandise-hiduka.git
            - git remote add github git@github.com:brill3000/merchandise-hiduka.git
            - git fetch --tags github "+refs/*:refs/*"
            - git push github 'refs/heads/main'
    release/pre-release:
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: true
          script:
            - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
            - cd merchandise-hiduka.git
            - git remote add github git@github.com:brill3000/merchandise-hiduka.git
            - git fetch --tags github "+refs/*:refs/*"
            - git push github 'refs/heads/release/pre-release'

