pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
          - cd merchandise-hiduka.git
          - git remote add github git@github.com:brill3000/merchandise-hiduka.git
          - git fetch --tags github "+refs/*:refs/*"
          - git push --mirror github 'refs/heads/main' 'refs/heads/release/pre-release'
