pipelines:
  default:
    - step:
        name: Sync GitHub Mirror (Main Branch)
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
          - cd merchandise-hiduka.git
          - git init
          - git remote add origin git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
          - git fetch origin main
          - git push --mirror git@github.com:brill3000/merchandise-hiduka.git

    - step:
        name: Manual Approval for Pre-release Sync
        script:
          - echo "Please manually approve the sync of release/pre-release branch."

    - step:
        name: Sync GitHub Mirror (Release/Pre-release Branch)
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
          - cd merchandise-hiduka.git
          - git init
          - git remote add origin git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
          - git fetch origin release/pre-release
          - git push --mirror git@github.com:brill3000/merchandise-hiduka.git
