pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
          - cd merchandise-hiduka.git
          - git push --mirror git@github.com:hokelainteractive/merchandise-hiduka.git