pipelines:
  branches:
    main:
      - step:
          name: Sync Main Branch from Bitbucket to GitHub
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
            - cd merchandise-hiduka.git
            - git push git@github.com:brill3000/merchandise-hiduka.git main
    release/pre-release:
      - step:
          name: Sync Release Branch from Bitbucket to GitHub
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:hokelainteractive/merchandise-hiduka.git
            - cd merchandise-hiduka.git
            - |
              if git rev-parse --quiet --verify release/pre-release; then
                git checkout release/pre-release
                git pull origin release/pre-release
              else
                git checkout -b release/pre-release origin/release/pre-release
              fi
              git push git@github.com:brill3000/merchandise-hiduka.git release/pre-release
